<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<!-- 引入bootstrap的文件 -->
<script type="text/javascript" src="${pageContext.request.contextPath}/bootstrap/js/jquery.min.js"></script>
<link href="${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="${pageContext.request.contextPath}/bootstrap/js/bootstrap.min.js"></script>

<!-- 引入easyui的核心样式文件 -->
<!-- 在web-inf中的文件要使用${pageContext.request.contextPath}来访问外部文件 -->
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/easyui/themes/bootstrap/easyui.css">
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/easyui/themes/icon.css">
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/easyui/demo/demo.css">
<!-- 引入easyui的js文件 -->
<script type="text/javascript" src="${pageContext.request.contextPath}/easyui/jquery.easyui.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/easyui/locale/easyui-lang-zh_CN.js"></script>
<%-- 七牛官方脚本  --%>
<script src="${pageContext.request.contextPath}/luntan/Plupload/js/plupload.full.min.js"></script>
<script src="${pageContext.request.contextPath}/luntan/dist/qiniu.js"></script>